export const TOKEN_REQUEST_STARTED = 'TOKEN_REQUEST_STARTED';
export const TOKEN_REQUEST_SUCCESSFUL = 'TOKEN_REQUEST_SUCCESSFUL';
export const TOKEN_REQUEST_FAILED = 'TOKEN_REQUEST_FAILED';
export const QUESTION_REQUEST_STARTED = 'QUESTION_REQUEST_STARTED';
export const QUESTION_REQUEST_SUCCESSFUL = 'QUESTION_REQUEST_SUCCESSFUL';
export const QUESTION_REQUEST_FAILED = 'QUESTION_REQUEST_FAILED';
export const SAVE_PLAYER_INFO = 'SAVE_PLAYER_INFO';
