export const TOKEN_REQUEST_STARTED = 'TOKEN_REQUEST_STARTED';
export const TOKEN_REQUEST_SUCCESSFUL = 'TOKEN_REQUEST_SUCCESSFUL';
export const TOKEN_REQUEST_FAILED = 'TOKEN_REQUEST_FAILED';
export const SAVE_PLAYER_INFO = 'SAVE_PLAYER_INFO';
